/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.DAO;
import Forms.FormListarEstoqueDisponivel;
import Interfaces.FalhaException;
import Models.Conserto;
import Models.Estoque;
import Models.Pecasconserto;
import Models.Produto;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author oseas
 */
public class FormSelecionarProdutoOrdem extends javax.swing.JFrame {

    private Conserto conserto;

    public Conserto getConserto() {
        return conserto;
    }

    public void setConserto(Conserto conserto) {
        this.conserto = conserto;
        FormListarEstoqueDisponivel.setTabela(TABLE_PRODUTOS);
        FormListarEstoqueDisponivel.atualizar();
    }
    
    /**
     * Creates new form FormSelecionarProdutoOrdem
     */
    public FormSelecionarProdutoOrdem() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HEADER1 = new javax.swing.JPanel();
        TEXT_TITLE1 = new javax.swing.JLabel();
        TABLE = new javax.swing.JScrollPane();
        TABLE_PRODUTOS = new javax.swing.JTable();
        BUTTON_CONSULTAR = new javax.swing.JButton();
        INPUT_QUANTIDADE = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HEADER1.setBackground(new java.awt.Color(159, 172, 172));

        TEXT_TITLE1.setFont(new java.awt.Font("Arial", 1, 35)); // NOI18N
        TEXT_TITLE1.setForeground(new java.awt.Color(255, 255, 255));
        TEXT_TITLE1.setText("SELECIONE UM PRODUTO");

        javax.swing.GroupLayout HEADER1Layout = new javax.swing.GroupLayout(HEADER1);
        HEADER1.setLayout(HEADER1Layout);
        HEADER1Layout.setHorizontalGroup(
            HEADER1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HEADER1Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(TEXT_TITLE1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HEADER1Layout.setVerticalGroup(
            HEADER1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HEADER1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(TEXT_TITLE1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        TABLE_PRODUTOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Lote", "Nome Produto", "Qnt Disponível", "Valor"
            }
        ));
        TABLE_PRODUTOS.setToolTipText("");
        TABLE.setViewportView(TABLE_PRODUTOS);

        BUTTON_CONSULTAR.setBackground(new java.awt.Color(204, 204, 0));
        BUTTON_CONSULTAR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUTTON_CONSULTAR.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_CONSULTAR.setText("ADICIONAR");
        BUTTON_CONSULTAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON_CONSULTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_CONSULTARActionPerformed(evt);
            }
        });

        jLabel1.setText("Quantidade");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HEADER1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(TABLE, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(BUTTON_CONSULTAR, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(INPUT_QUANTIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HEADER1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TABLE, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_QUANTIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(BUTTON_CONSULTAR, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BUTTON_CONSULTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_CONSULTARActionPerformed
        int linha = TABLE_PRODUTOS.getSelectedRow();
       int codigoLote = Integer.parseInt(TABLE_PRODUTOS.getValueAt(linha,0).toString());
       Estoque estoque = DAO.getInstance().find(Estoque.class, codigoLote);
       if(estoque instanceof Estoque && (Integer.parseInt(INPUT_QUANTIDADE.getText()) > 0) && (Integer.parseInt(INPUT_QUANTIDADE.getText()) <= estoque.getEstQuantidade()) ){
         Pecasconserto pecasconserto = new Pecasconserto();
         pecasconserto.setConserto(conserto);
         pecasconserto.setEstoque(estoque);
         pecasconserto.setPcQuantidade(Integer.parseInt(INPUT_QUANTIDADE.getText()));
            try {
                DAO.getInstance().getTransaction().begin();
                pecasconserto.salvar();
                estoque.setEstQuantidade(estoque.getEstQuantidade() - (Integer.parseInt(INPUT_QUANTIDADE.getText())));
                estoque.salvar();
                DAO.getInstance().getTransaction().commit();
                this.setVisible(false);
            } catch (FalhaException ex) {
                if(DAO.getInstance().getTransaction().isActive()){
                    DAO.getInstance().getTransaction().rollback();
                }
            }
       }
    }//GEN-LAST:event_BUTTON_CONSULTARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSelecionarProdutoOrdem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSelecionarProdutoOrdem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSelecionarProdutoOrdem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSelecionarProdutoOrdem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSelecionarProdutoOrdem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUTTON_CONSULTAR;
    private javax.swing.JPanel HEADER1;
    private javax.swing.JTextField INPUT_QUANTIDADE;
    private javax.swing.JScrollPane TABLE;
    private javax.swing.JTable TABLE_PRODUTOS;
    private javax.swing.JLabel TEXT_TITLE1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
