/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Views;

/**
 *
 * @author oseas
 */
public class FormListarNota extends javax.swing.JInternalFrame {

    private FormCadastrarNota formCadastrarNota;
    /**
     * Creates new form FormListarNota
     */
    public FormListarNota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BUTTON_PESQUISAR = new javax.swing.JButton();
        HEADER = new javax.swing.JPanel();
        TEXT_TITLE = new javax.swing.JLabel();
        BUTTON_CONSULTAR = new javax.swing.JButton();
        TABLE = new javax.swing.JScrollPane();
        TABLE_PRODUTOS = new javax.swing.JTable();
        INPUT_PESQUISA = new javax.swing.JTextPane();
        BUTTON_CADASTRAR = new javax.swing.JButton();
        TEXT_PESQUISA = new javax.swing.JLabel();

        BUTTON_PESQUISAR.setBackground(new java.awt.Color(0, 204, 255));
        BUTTON_PESQUISAR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUTTON_PESQUISAR.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_PESQUISAR.setText("PESQUISAR");
        BUTTON_PESQUISAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON_PESQUISAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_PESQUISARActionPerformed(evt);
            }
        });

        HEADER.setBackground(new java.awt.Color(159, 172, 172));

        TEXT_TITLE.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        TEXT_TITLE.setForeground(new java.awt.Color(255, 255, 255));
        TEXT_TITLE.setText("LISTAR NOTAS");

        javax.swing.GroupLayout HEADERLayout = new javax.swing.GroupLayout(HEADER);
        HEADER.setLayout(HEADERLayout);
        HEADERLayout.setHorizontalGroup(
            HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HEADERLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TEXT_TITLE)
                .addContainerGap())
        );
        HEADERLayout.setVerticalGroup(
            HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TEXT_TITLE, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        BUTTON_CONSULTAR.setBackground(new java.awt.Color(0, 204, 204));
        BUTTON_CONSULTAR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUTTON_CONSULTAR.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_CONSULTAR.setText("CONSULTAR");
        BUTTON_CONSULTAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON_CONSULTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_CONSULTARActionPerformed(evt);
            }
        });

        TABLE_PRODUTOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NNF", "Data Compra", "Data Entrada"
            }
        ));
        TABLE.setViewportView(TABLE_PRODUTOS);

        INPUT_PESQUISA.setBorder(null);
        INPUT_PESQUISA.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_PESQUISA.setToolTipText("Quantidade");
        INPUT_PESQUISA.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        BUTTON_CADASTRAR.setBackground(new java.awt.Color(0, 102, 0));
        BUTTON_CADASTRAR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUTTON_CADASTRAR.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_CADASTRAR.setText("CADASTRAR");
        BUTTON_CADASTRAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON_CADASTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_CADASTRARActionPerformed(evt);
            }
        });

        TEXT_PESQUISA.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        TEXT_PESQUISA.setText("Pequisa:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HEADER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TEXT_PESQUISA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(INPUT_PESQUISA)
                                .addGap(18, 18, 18)
                                .addComponent(BUTTON_PESQUISAR, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TABLE, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(BUTTON_CONSULTAR, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BUTTON_CADASTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HEADER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BUTTON_PESQUISAR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(INPUT_PESQUISA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_PESQUISA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(TABLE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BUTTON_CONSULTAR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUTTON_CADASTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BUTTON_PESQUISARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_PESQUISARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BUTTON_PESQUISARActionPerformed

    private void BUTTON_CONSULTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_CONSULTARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BUTTON_CONSULTARActionPerformed

    private void BUTTON_CADASTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_CADASTRARActionPerformed
        if(!(this.formCadastrarNota instanceof FormCadastrarNota)){
            this.formCadastrarNota = new FormCadastrarNota();
        }
        this.formCadastrarNota.setVisible(true);
    }//GEN-LAST:event_BUTTON_CADASTRARActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUTTON_CADASTRAR;
    private javax.swing.JButton BUTTON_CONSULTAR;
    private javax.swing.JButton BUTTON_PESQUISAR;
    private javax.swing.JPanel HEADER;
    private javax.swing.JTextPane INPUT_PESQUISA;
    private javax.swing.JScrollPane TABLE;
    private javax.swing.JTable TABLE_PRODUTOS;
    private javax.swing.JLabel TEXT_PESQUISA;
    private javax.swing.JLabel TEXT_TITLE;
    // End of variables declaration//GEN-END:variables
}
