/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Views;

import Controllers.ControllerFornecedor;
import Controllers.DAO;
import Forms.FormListarFornecedor;
import Forms.FormListarNota;
import Interfaces.FalhaException;
import Models.Fornecedor;
import Models.Nota;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author oseas
 */
public class FormConsultarFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form FormConsultarFornecedor
     */
    
    private Fornecedor fornecedor;
    private final ControllerFornecedor controllerFornecedor = new ControllerFornecedor();
    private final FormConsultarNota formConsultarNota = new FormConsultarNota();
    private final FormCadastrarNota formCadastrarNota = new FormCadastrarNota();
    private final FormAtualizarFornecedor formAtualizarFornecedor = new FormAtualizarFornecedor();

    public Fornecedor getFornecedor() {
        return fornecedor;
    }

    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
        controllerFornecedor.setFornecedor(fornecedor);
        controllerFornecedor.preencherForm(INPUT_NOME_FANTASIA, INPUT_RAZAO_SOCIAL, INPUT_CNPJ, INPUT_IE);
        FormListarNota.setTabela(TABLE);
        FormListarNota.setFornecedor(fornecedor);
        FormListarNota.atualizar();
        
    }
    
    public FormConsultarFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HEADER = new javax.swing.JPanel();
        TEXT_TITLE = new javax.swing.JLabel();
        BG_INPUT_IE = new javax.swing.JPanel();
        TEXT_IE = new javax.swing.JLabel();
        INPUT_IE = new javax.swing.JTextPane();
        BG_INPUT_RAZAO_SOCIAL = new javax.swing.JPanel();
        TEXT_RAZAO_SOCIAL = new javax.swing.JLabel();
        INPUT_RAZAO_SOCIAL = new javax.swing.JTextPane();
        BUTTON_EXCLUIR = new javax.swing.JButton();
        BG_INPUT_CNPJ = new javax.swing.JPanel();
        TEXT_CNPJ = new javax.swing.JLabel();
        INPUT_CNPJ = new javax.swing.JTextPane();
        BG_INPUT_NOME_FANTASIA = new javax.swing.JPanel();
        TEXT_NOME_FANTASIA = new javax.swing.JLabel();
        INPUT_NOME_FANTASIA = new javax.swing.JTextPane();
        BUTTON_EDITAR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLE = new javax.swing.JTable();
        BUTTON_EDITAR1 = new javax.swing.JButton();
        BUTTON_EDITAR2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        HEADER.setBackground(new java.awt.Color(159, 172, 172));

        TEXT_TITLE.setFont(new java.awt.Font("Arial", 1, 35)); // NOI18N
        TEXT_TITLE.setForeground(new java.awt.Color(255, 255, 255));
        TEXT_TITLE.setText("CONSULTAR FORNECEDOR");

        javax.swing.GroupLayout HEADERLayout = new javax.swing.GroupLayout(HEADER);
        HEADER.setLayout(HEADERLayout);
        HEADERLayout.setHorizontalGroup(
            HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HEADERLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(TEXT_TITLE)
                .addGap(250, 250, 250))
        );
        HEADERLayout.setVerticalGroup(
            HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HEADERLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(TEXT_TITLE, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        BG_INPUT_IE.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_IE.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_IE.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_IE.setText("IE:");

        INPUT_IE.setBorder(null);
        INPUT_IE.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_IE.setToolTipText("Quantidade");
        INPUT_IE.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        INPUT_IE.setEnabled(false);

        javax.swing.GroupLayout BG_INPUT_IELayout = new javax.swing.GroupLayout(BG_INPUT_IE);
        BG_INPUT_IE.setLayout(BG_INPUT_IELayout);
        BG_INPUT_IELayout.setHorizontalGroup(
            BG_INPUT_IELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_IELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXT_IE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_IE, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );
        BG_INPUT_IELayout.setVerticalGroup(
            BG_INPUT_IELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_IELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_INPUT_IELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_IE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_IE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BG_INPUT_RAZAO_SOCIAL.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_RAZAO_SOCIAL.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_RAZAO_SOCIAL.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_RAZAO_SOCIAL.setText("Razão Social:");

        INPUT_RAZAO_SOCIAL.setBorder(null);
        INPUT_RAZAO_SOCIAL.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_RAZAO_SOCIAL.setToolTipText("Quantidade");
        INPUT_RAZAO_SOCIAL.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        INPUT_RAZAO_SOCIAL.setEnabled(false);

        javax.swing.GroupLayout BG_INPUT_RAZAO_SOCIALLayout = new javax.swing.GroupLayout(BG_INPUT_RAZAO_SOCIAL);
        BG_INPUT_RAZAO_SOCIAL.setLayout(BG_INPUT_RAZAO_SOCIALLayout);
        BG_INPUT_RAZAO_SOCIALLayout.setHorizontalGroup(
            BG_INPUT_RAZAO_SOCIALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_RAZAO_SOCIALLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXT_RAZAO_SOCIAL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_RAZAO_SOCIAL)
                .addContainerGap())
        );
        BG_INPUT_RAZAO_SOCIALLayout.setVerticalGroup(
            BG_INPUT_RAZAO_SOCIALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_RAZAO_SOCIALLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_INPUT_RAZAO_SOCIALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_RAZAO_SOCIAL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_RAZAO_SOCIAL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BUTTON_EXCLUIR.setBackground(new java.awt.Color(255, 51, 51));
        BUTTON_EXCLUIR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUTTON_EXCLUIR.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_EXCLUIR.setText("EXCLUIR");
        BUTTON_EXCLUIR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON_EXCLUIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_EXCLUIRActionPerformed(evt);
            }
        });

        BG_INPUT_CNPJ.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_CNPJ.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_CNPJ.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_CNPJ.setText("CNPJ:");

        INPUT_CNPJ.setBorder(null);
        INPUT_CNPJ.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_CNPJ.setToolTipText("Quantidade");
        INPUT_CNPJ.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        INPUT_CNPJ.setEnabled(false);

        javax.swing.GroupLayout BG_INPUT_CNPJLayout = new javax.swing.GroupLayout(BG_INPUT_CNPJ);
        BG_INPUT_CNPJ.setLayout(BG_INPUT_CNPJLayout);
        BG_INPUT_CNPJLayout.setHorizontalGroup(
            BG_INPUT_CNPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_CNPJLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TEXT_CNPJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        BG_INPUT_CNPJLayout.setVerticalGroup(
            BG_INPUT_CNPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_CNPJLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_INPUT_CNPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BG_INPUT_NOME_FANTASIA.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_NOME_FANTASIA.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_NOME_FANTASIA.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_NOME_FANTASIA.setText("Nome Fantasia:");

        INPUT_NOME_FANTASIA.setBorder(null);
        INPUT_NOME_FANTASIA.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_NOME_FANTASIA.setToolTipText("Quantidade");
        INPUT_NOME_FANTASIA.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        INPUT_NOME_FANTASIA.setEnabled(false);
        INPUT_NOME_FANTASIA.setMaximumSize(new java.awt.Dimension(62, 38));

        javax.swing.GroupLayout BG_INPUT_NOME_FANTASIALayout = new javax.swing.GroupLayout(BG_INPUT_NOME_FANTASIA);
        BG_INPUT_NOME_FANTASIA.setLayout(BG_INPUT_NOME_FANTASIALayout);
        BG_INPUT_NOME_FANTASIALayout.setHorizontalGroup(
            BG_INPUT_NOME_FANTASIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_NOME_FANTASIALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXT_NOME_FANTASIA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_NOME_FANTASIA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BG_INPUT_NOME_FANTASIALayout.setVerticalGroup(
            BG_INPUT_NOME_FANTASIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_NOME_FANTASIALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_INPUT_NOME_FANTASIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_NOME_FANTASIA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_NOME_FANTASIA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BUTTON_EDITAR.setBackground(new java.awt.Color(0, 51, 153));
        BUTTON_EDITAR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUTTON_EDITAR.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_EDITAR.setText("CADASTRAR");
        BUTTON_EDITAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON_EDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_EDITARActionPerformed(evt);
            }
        });

        TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Data Compra", "Data Entrada"
            }
        ));
        jScrollPane1.setViewportView(TABLE);

        BUTTON_EDITAR1.setBackground(new java.awt.Color(0, 204, 204));
        BUTTON_EDITAR1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUTTON_EDITAR1.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_EDITAR1.setText("EDITAR");
        BUTTON_EDITAR1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON_EDITAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_EDITAR1ActionPerformed(evt);
            }
        });

        BUTTON_EDITAR2.setBackground(new java.awt.Color(51, 204, 0));
        BUTTON_EDITAR2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUTTON_EDITAR2.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_EDITAR2.setText("CONSULTAR");
        BUTTON_EDITAR2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON_EDITAR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_EDITAR2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Notas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HEADER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(449, 449, 449))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(BUTTON_EDITAR2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(BUTTON_EDITAR, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(19, 19, 19))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BG_INPUT_NOME_FANTASIA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BG_INPUT_RAZAO_SOCIAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BG_INPUT_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BG_INPUT_IE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(148, 148, 148))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(BUTTON_EDITAR1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BUTTON_EXCLUIR, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(116, 116, 116)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HEADER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(BG_INPUT_NOME_FANTASIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BG_INPUT_RAZAO_SOCIAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BG_INPUT_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BG_INPUT_IE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BUTTON_EDITAR, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUTTON_EDITAR2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BUTTON_EXCLUIR, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUTTON_EDITAR1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BUTTON_EXCLUIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_EXCLUIRActionPerformed
        try {
            this.getFornecedor().excluir();
            this.setVisible(false);
            FormListarFornecedor.atualizar();
        } catch (FalhaException ex) {
        }
    }//GEN-LAST:event_BUTTON_EXCLUIRActionPerformed

    private void BUTTON_EDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_EDITARActionPerformed
        formCadastrarNota.setVisible(true);
        formCadastrarNota.setFornecedor(this.fornecedor);
        this.setVisible(false);
    }//GEN-LAST:event_BUTTON_EDITARActionPerformed

    private void BUTTON_EDITAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_EDITAR1ActionPerformed
        formAtualizarFornecedor.setFornecedor(fornecedor);
        formAtualizarFornecedor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BUTTON_EDITAR1ActionPerformed

    private void BUTTON_EDITAR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_EDITAR2ActionPerformed
       int linha = TABLE.getSelectedRow();
       int codigoProduto = Integer.parseInt(TABLE.getValueAt(linha,0).toString());
       Nota nota = DAO.getInstance().find(Nota.class, codigoProduto);
       if(nota instanceof Nota){
            this.formConsultarNota.setNota(nota);
            this.formConsultarNota.setVisible(true);
       }
    }//GEN-LAST:event_BUTTON_EDITAR2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG_INPUT_CNPJ;
    private javax.swing.JPanel BG_INPUT_IE;
    private javax.swing.JPanel BG_INPUT_NOME_FANTASIA;
    private javax.swing.JPanel BG_INPUT_RAZAO_SOCIAL;
    private javax.swing.JButton BUTTON_EDITAR;
    private javax.swing.JButton BUTTON_EDITAR1;
    private javax.swing.JButton BUTTON_EDITAR2;
    private javax.swing.JButton BUTTON_EXCLUIR;
    private javax.swing.JPanel HEADER;
    private javax.swing.JTextPane INPUT_CNPJ;
    private javax.swing.JTextPane INPUT_IE;
    private javax.swing.JTextPane INPUT_NOME_FANTASIA;
    private javax.swing.JTextPane INPUT_RAZAO_SOCIAL;
    private javax.swing.JTable TABLE;
    private javax.swing.JLabel TEXT_CNPJ;
    private javax.swing.JLabel TEXT_IE;
    private javax.swing.JLabel TEXT_NOME_FANTASIA;
    private javax.swing.JLabel TEXT_RAZAO_SOCIAL;
    private javax.swing.JLabel TEXT_TITLE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
