/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Views;

/**
 *
 * @author oseas
 */
public class FormAtualizarFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form FormAtualizarFornecedor
     */
    public FormAtualizarFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BUTTON_ATUALIZAR = new javax.swing.JButton();
        BG_INPUT_CNPJ = new javax.swing.JPanel();
        TEXT_CNPJ = new javax.swing.JLabel();
        INPUT_CNPJ = new javax.swing.JTextPane();
        BG_INPUT_NOME_FANTASIA = new javax.swing.JPanel();
        TEXT_NOME_FANTASIA = new javax.swing.JLabel();
        INPUT_NOME_FANTASIA = new javax.swing.JTextPane();
        BG_INPUT_IE = new javax.swing.JPanel();
        TEXT_IE = new javax.swing.JLabel();
        INPUT_IE = new javax.swing.JTextPane();
        BG_INPUT_RAZAO_SOCIAL = new javax.swing.JPanel();
        TEXT_RAZAO_SOCIAL = new javax.swing.JLabel();
        INPUT_RAZAO_SOCIAL = new javax.swing.JTextPane();
        HEADER = new javax.swing.JPanel();
        TEXT_TITLE = new javax.swing.JLabel();

        BUTTON_ATUALIZAR.setBackground(new java.awt.Color(0, 204, 0));
        BUTTON_ATUALIZAR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUTTON_ATUALIZAR.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_ATUALIZAR.setText("ATUALIZAR");
        BUTTON_ATUALIZAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON_ATUALIZAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_ATUALIZARActionPerformed(evt);
            }
        });

        BG_INPUT_CNPJ.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_CNPJ.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_CNPJ.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_CNPJ.setText("CNPJ:");

        INPUT_CNPJ.setBorder(null);
        INPUT_CNPJ.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_CNPJ.setToolTipText("Quantidade");
        INPUT_CNPJ.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout BG_INPUT_CNPJLayout = new javax.swing.GroupLayout(BG_INPUT_CNPJ);
        BG_INPUT_CNPJ.setLayout(BG_INPUT_CNPJLayout);
        BG_INPUT_CNPJLayout.setHorizontalGroup(
            BG_INPUT_CNPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_CNPJLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TEXT_CNPJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        BG_INPUT_CNPJLayout.setVerticalGroup(
            BG_INPUT_CNPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_CNPJLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_INPUT_CNPJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BG_INPUT_NOME_FANTASIA.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_NOME_FANTASIA.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_NOME_FANTASIA.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_NOME_FANTASIA.setText("Nome Fantasia:");

        INPUT_NOME_FANTASIA.setBorder(null);
        INPUT_NOME_FANTASIA.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_NOME_FANTASIA.setToolTipText("Quantidade");
        INPUT_NOME_FANTASIA.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        INPUT_NOME_FANTASIA.setMaximumSize(new java.awt.Dimension(62, 38));

        javax.swing.GroupLayout BG_INPUT_NOME_FANTASIALayout = new javax.swing.GroupLayout(BG_INPUT_NOME_FANTASIA);
        BG_INPUT_NOME_FANTASIA.setLayout(BG_INPUT_NOME_FANTASIALayout);
        BG_INPUT_NOME_FANTASIALayout.setHorizontalGroup(
            BG_INPUT_NOME_FANTASIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_NOME_FANTASIALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXT_NOME_FANTASIA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_NOME_FANTASIA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BG_INPUT_NOME_FANTASIALayout.setVerticalGroup(
            BG_INPUT_NOME_FANTASIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_NOME_FANTASIALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_INPUT_NOME_FANTASIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_NOME_FANTASIA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_NOME_FANTASIA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BG_INPUT_IE.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_IE.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_IE.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_IE.setText("IE:");

        INPUT_IE.setBorder(null);
        INPUT_IE.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_IE.setToolTipText("Quantidade");
        INPUT_IE.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout BG_INPUT_IELayout = new javax.swing.GroupLayout(BG_INPUT_IE);
        BG_INPUT_IE.setLayout(BG_INPUT_IELayout);
        BG_INPUT_IELayout.setHorizontalGroup(
            BG_INPUT_IELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_IELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXT_IE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_IE, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );
        BG_INPUT_IELayout.setVerticalGroup(
            BG_INPUT_IELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_IELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_INPUT_IELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_IE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_IE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BG_INPUT_RAZAO_SOCIAL.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_RAZAO_SOCIAL.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_RAZAO_SOCIAL.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_RAZAO_SOCIAL.setText("Razão Social:");

        INPUT_RAZAO_SOCIAL.setBorder(null);
        INPUT_RAZAO_SOCIAL.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_RAZAO_SOCIAL.setToolTipText("Quantidade");
        INPUT_RAZAO_SOCIAL.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout BG_INPUT_RAZAO_SOCIALLayout = new javax.swing.GroupLayout(BG_INPUT_RAZAO_SOCIAL);
        BG_INPUT_RAZAO_SOCIAL.setLayout(BG_INPUT_RAZAO_SOCIALLayout);
        BG_INPUT_RAZAO_SOCIALLayout.setHorizontalGroup(
            BG_INPUT_RAZAO_SOCIALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_RAZAO_SOCIALLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXT_RAZAO_SOCIAL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_RAZAO_SOCIAL, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addContainerGap())
        );
        BG_INPUT_RAZAO_SOCIALLayout.setVerticalGroup(
            BG_INPUT_RAZAO_SOCIALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_RAZAO_SOCIALLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_INPUT_RAZAO_SOCIALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_RAZAO_SOCIAL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_RAZAO_SOCIAL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        HEADER.setBackground(new java.awt.Color(159, 172, 172));

        TEXT_TITLE.setFont(new java.awt.Font("Arial", 1, 35)); // NOI18N
        TEXT_TITLE.setForeground(new java.awt.Color(255, 255, 255));
        TEXT_TITLE.setText("Atualizar Fornecedor");

        javax.swing.GroupLayout HEADERLayout = new javax.swing.GroupLayout(HEADER);
        HEADER.setLayout(HEADERLayout);
        HEADERLayout.setHorizontalGroup(
            HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HEADERLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(TEXT_TITLE)
                .addGap(250, 250, 250))
        );
        HEADERLayout.setVerticalGroup(
            HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HEADERLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(TEXT_TITLE, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HEADER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BG_INPUT_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BG_INPUT_IE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BG_INPUT_NOME_FANTASIA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BG_INPUT_RAZAO_SOCIAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(BUTTON_ATUALIZAR, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HEADER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(BG_INPUT_NOME_FANTASIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BG_INPUT_RAZAO_SOCIAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BG_INPUT_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BG_INPUT_IE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(BUTTON_ATUALIZAR, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BUTTON_ATUALIZARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_ATUALIZARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BUTTON_ATUALIZARActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG_INPUT_CNPJ;
    private javax.swing.JPanel BG_INPUT_IE;
    private javax.swing.JPanel BG_INPUT_NOME_FANTASIA;
    private javax.swing.JPanel BG_INPUT_RAZAO_SOCIAL;
    private javax.swing.JButton BUTTON_ATUALIZAR;
    private javax.swing.JPanel HEADER;
    private javax.swing.JTextPane INPUT_CNPJ;
    private javax.swing.JTextPane INPUT_IE;
    private javax.swing.JTextPane INPUT_NOME_FANTASIA;
    private javax.swing.JTextPane INPUT_RAZAO_SOCIAL;
    private javax.swing.JLabel TEXT_CNPJ;
    private javax.swing.JLabel TEXT_IE;
    private javax.swing.JLabel TEXT_NOME_FANTASIA;
    private javax.swing.JLabel TEXT_RAZAO_SOCIAL;
    private javax.swing.JLabel TEXT_TITLE;
    // End of variables declaration//GEN-END:variables
}
