/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Views;

import Controllers.ControllerCliente;
import Interfaces.FalhaException;
import br.dev.lomm.automecanicapoo.database.Cliente;
import br.dev.lomm.automecanicapoo.database.Funcionario;

/**
 *
 * @author oseas
 */
public class FormConsultarCliente extends javax.swing.JFrame {

    private FormCadastrarOrdemDeServico formCadastrarOrdemDeServico = new FormCadastrarOrdemDeServico();
    private final ControllerCliente controllerCliente = new ControllerCliente();
    private Cliente cliente;
    
    /**
     * Creates new form FormConsultarCliente
     */
    public FormConsultarCliente() {
        initComponents();
    }

    public void setCliente(Cliente cliente){
        this.cliente = cliente;
        controllerCliente.setCliente(cliente);
        controllerCliente.preencherForm(INPUT_NOME, INPUT_CPF, INPUT_DTNASCIMENTO, INPUT_EMAIL, INPUT_LOGRADOURO, INPUT_CEP, INPUT_BAIRRO, INPUT_CIDADE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG_INPUT_DTNASCIMENTO = new javax.swing.JPanel();
        TEXT_DTNASCIMENTO = new javax.swing.JLabel();
        INPUT_DTNASCIMENTO = new com.toedter.calendar.JDateChooser();
        HEADER = new javax.swing.JPanel();
        TEXT_TITLE = new javax.swing.JLabel();
        BUTTON_EDITAR = new javax.swing.JButton();
        BG_INPUT_LOGRADOURO = new javax.swing.JPanel();
        TEXT_LOGRADOURO = new javax.swing.JLabel();
        INPUT_LOGRADOURO = new javax.swing.JTextPane();
        BG_INPUT_CEP = new javax.swing.JPanel();
        TEXT_CEP = new javax.swing.JLabel();
        INPUT_CEP = new javax.swing.JTextPane();
        BG_INPUT_CPF = new javax.swing.JPanel();
        TEXT_CPF = new javax.swing.JLabel();
        INPUT_CPF = new javax.swing.JTextPane();
        BG_INPUT_EMAIL = new javax.swing.JPanel();
        TEXT_EMAIL = new javax.swing.JLabel();
        INPUT_EMAIL = new javax.swing.JTextPane();
        BG_INPUT_NOME = new javax.swing.JPanel();
        TEXT_NOME = new javax.swing.JLabel();
        INPUT_NOME = new javax.swing.JTextPane();
        BUTTON_EXCLUIR = new javax.swing.JButton();
        BG_INPUT_BAIRRO = new javax.swing.JPanel();
        TEXT_BAIRRO = new javax.swing.JLabel();
        INPUT_BAIRRO = new javax.swing.JTextPane();
        BG_INPUT_CIDADE = new javax.swing.JPanel();
        TEXT_CIDADE = new javax.swing.JLabel();
        INPUT_CIDADE = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TEXT_TITLE1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        TEXT_TITLE2 = new javax.swing.JLabel();
        BUTTON_EDITAR1 = new javax.swing.JButton();
        BUTTON_EDITAR2 = new javax.swing.JButton();
        BUTTON_EDITAR3 = new javax.swing.JButton();

        BG_INPUT_DTNASCIMENTO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_DTNASCIMENTO.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_DTNASCIMENTO.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_DTNASCIMENTO.setText("Data Nascimento:");

        INPUT_DTNASCIMENTO.setEnabled(false);

        javax.swing.GroupLayout BG_INPUT_DTNASCIMENTOLayout = new javax.swing.GroupLayout(BG_INPUT_DTNASCIMENTO);
        BG_INPUT_DTNASCIMENTO.setLayout(BG_INPUT_DTNASCIMENTOLayout);
        BG_INPUT_DTNASCIMENTOLayout.setHorizontalGroup(
            BG_INPUT_DTNASCIMENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_DTNASCIMENTOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXT_DTNASCIMENTO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(INPUT_DTNASCIMENTO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BG_INPUT_DTNASCIMENTOLayout.setVerticalGroup(
            BG_INPUT_DTNASCIMENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_DTNASCIMENTOLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(BG_INPUT_DTNASCIMENTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TEXT_DTNASCIMENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(INPUT_DTNASCIMENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        HEADER.setBackground(new java.awt.Color(159, 172, 172));

        TEXT_TITLE.setFont(new java.awt.Font("Arial", 1, 35)); // NOI18N
        TEXT_TITLE.setForeground(new java.awt.Color(255, 255, 255));
        TEXT_TITLE.setText("CONSULTAR CLIENTE");

        javax.swing.GroupLayout HEADERLayout = new javax.swing.GroupLayout(HEADER);
        HEADER.setLayout(HEADERLayout);
        HEADERLayout.setHorizontalGroup(
            HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HEADERLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TEXT_TITLE)
                .addGap(463, 463, 463))
        );
        HEADERLayout.setVerticalGroup(
            HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HEADERLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(TEXT_TITLE, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        BUTTON_EDITAR.setBackground(new java.awt.Color(0, 204, 204));
        BUTTON_EDITAR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUTTON_EDITAR.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_EDITAR.setText("EDITAR");
        BUTTON_EDITAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON_EDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_EDITARActionPerformed(evt);
            }
        });

        BG_INPUT_LOGRADOURO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_LOGRADOURO.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_LOGRADOURO.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_LOGRADOURO.setText("Logradouro:");

        INPUT_LOGRADOURO.setBorder(null);
        INPUT_LOGRADOURO.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_LOGRADOURO.setToolTipText("Quantidade");
        INPUT_LOGRADOURO.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        INPUT_LOGRADOURO.setEnabled(false);

        javax.swing.GroupLayout BG_INPUT_LOGRADOUROLayout = new javax.swing.GroupLayout(BG_INPUT_LOGRADOURO);
        BG_INPUT_LOGRADOURO.setLayout(BG_INPUT_LOGRADOUROLayout);
        BG_INPUT_LOGRADOUROLayout.setHorizontalGroup(
            BG_INPUT_LOGRADOUROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_LOGRADOUROLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXT_LOGRADOURO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_LOGRADOURO, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addContainerGap())
        );
        BG_INPUT_LOGRADOUROLayout.setVerticalGroup(
            BG_INPUT_LOGRADOUROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_LOGRADOUROLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_INPUT_LOGRADOUROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_LOGRADOURO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_LOGRADOURO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BG_INPUT_CEP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_CEP.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_CEP.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_CEP.setText("CEP:");

        INPUT_CEP.setBorder(null);
        INPUT_CEP.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_CEP.setToolTipText("Quantidade");
        INPUT_CEP.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        INPUT_CEP.setEnabled(false);

        javax.swing.GroupLayout BG_INPUT_CEPLayout = new javax.swing.GroupLayout(BG_INPUT_CEP);
        BG_INPUT_CEP.setLayout(BG_INPUT_CEPLayout);
        BG_INPUT_CEPLayout.setHorizontalGroup(
            BG_INPUT_CEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_CEPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXT_CEP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_CEP)
                .addContainerGap())
        );
        BG_INPUT_CEPLayout.setVerticalGroup(
            BG_INPUT_CEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_CEPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_INPUT_CEPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BG_INPUT_CPF.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_CPF.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_CPF.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_CPF.setText("CPF:");

        INPUT_CPF.setBorder(null);
        INPUT_CPF.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_CPF.setToolTipText("Quantidade");
        INPUT_CPF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        INPUT_CPF.setEnabled(false);

        javax.swing.GroupLayout BG_INPUT_CPFLayout = new javax.swing.GroupLayout(BG_INPUT_CPF);
        BG_INPUT_CPF.setLayout(BG_INPUT_CPFLayout);
        BG_INPUT_CPFLayout.setHorizontalGroup(
            BG_INPUT_CPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_CPFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXT_CPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_CPF, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );
        BG_INPUT_CPFLayout.setVerticalGroup(
            BG_INPUT_CPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_CPFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_INPUT_CPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BG_INPUT_EMAIL.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_EMAIL.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_EMAIL.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_EMAIL.setText("Email:");

        INPUT_EMAIL.setBorder(null);
        INPUT_EMAIL.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_EMAIL.setToolTipText("Quantidade");
        INPUT_EMAIL.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        INPUT_EMAIL.setEnabled(false);

        javax.swing.GroupLayout BG_INPUT_EMAILLayout = new javax.swing.GroupLayout(BG_INPUT_EMAIL);
        BG_INPUT_EMAIL.setLayout(BG_INPUT_EMAILLayout);
        BG_INPUT_EMAILLayout.setHorizontalGroup(
            BG_INPUT_EMAILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_EMAILLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXT_EMAIL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_EMAIL)
                .addContainerGap())
        );
        BG_INPUT_EMAILLayout.setVerticalGroup(
            BG_INPUT_EMAILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_EMAILLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_INPUT_EMAILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BG_INPUT_NOME.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_NOME.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_NOME.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_NOME.setText("Nome:");

        INPUT_NOME.setBorder(null);
        INPUT_NOME.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_NOME.setToolTipText("Quantidade");
        INPUT_NOME.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        INPUT_NOME.setEnabled(false);
        INPUT_NOME.setMaximumSize(new java.awt.Dimension(62, 38));

        javax.swing.GroupLayout BG_INPUT_NOMELayout = new javax.swing.GroupLayout(BG_INPUT_NOME);
        BG_INPUT_NOME.setLayout(BG_INPUT_NOMELayout);
        BG_INPUT_NOMELayout.setHorizontalGroup(
            BG_INPUT_NOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_NOMELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXT_NOME)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_NOME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BG_INPUT_NOMELayout.setVerticalGroup(
            BG_INPUT_NOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_NOMELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_INPUT_NOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_NOME, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_NOME, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BUTTON_EXCLUIR.setBackground(new java.awt.Color(255, 51, 51));
        BUTTON_EXCLUIR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUTTON_EXCLUIR.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_EXCLUIR.setText("EXCLUIR");
        BUTTON_EXCLUIR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON_EXCLUIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_EXCLUIRActionPerformed(evt);
            }
        });

        BG_INPUT_BAIRRO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_BAIRRO.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_BAIRRO.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_BAIRRO.setText("Bairro:");

        INPUT_BAIRRO.setBorder(null);
        INPUT_BAIRRO.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_BAIRRO.setToolTipText("Quantidade");
        INPUT_BAIRRO.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        INPUT_BAIRRO.setEnabled(false);

        javax.swing.GroupLayout BG_INPUT_BAIRROLayout = new javax.swing.GroupLayout(BG_INPUT_BAIRRO);
        BG_INPUT_BAIRRO.setLayout(BG_INPUT_BAIRROLayout);
        BG_INPUT_BAIRROLayout.setHorizontalGroup(
            BG_INPUT_BAIRROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_BAIRROLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXT_BAIRRO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_BAIRRO, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );
        BG_INPUT_BAIRROLayout.setVerticalGroup(
            BG_INPUT_BAIRROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_BAIRROLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_INPUT_BAIRROLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_BAIRRO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_BAIRRO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BG_INPUT_CIDADE.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_CIDADE.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_CIDADE.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_CIDADE.setText("Cidade:");

        INPUT_CIDADE.setBorder(null);
        INPUT_CIDADE.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_CIDADE.setToolTipText("Quantidade");
        INPUT_CIDADE.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        INPUT_CIDADE.setEnabled(false);

        javax.swing.GroupLayout BG_INPUT_CIDADELayout = new javax.swing.GroupLayout(BG_INPUT_CIDADE);
        BG_INPUT_CIDADE.setLayout(BG_INPUT_CIDADELayout);
        BG_INPUT_CIDADELayout.setHorizontalGroup(
            BG_INPUT_CIDADELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_CIDADELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXT_CIDADE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_CIDADE, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addContainerGap())
        );
        BG_INPUT_CIDADELayout.setVerticalGroup(
            BG_INPUT_CIDADELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_CIDADELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_INPUT_CIDADELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TEXT_CIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(INPUT_CIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "KM", "Modelo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        TEXT_TITLE1.setFont(new java.awt.Font("Arial", 1, 35)); // NOI18N
        TEXT_TITLE1.setText("Veiculos");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Status", "Veiculo", "Data"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        TEXT_TITLE2.setFont(new java.awt.Font("Arial", 1, 35)); // NOI18N
        TEXT_TITLE2.setText("Serviços");

        BUTTON_EDITAR1.setBackground(new java.awt.Color(51, 0, 204));
        BUTTON_EDITAR1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUTTON_EDITAR1.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_EDITAR1.setText("GERAR ORDEM SERVIÇO");
        BUTTON_EDITAR1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON_EDITAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_EDITAR1ActionPerformed(evt);
            }
        });

        BUTTON_EDITAR2.setBackground(new java.awt.Color(0, 204, 51));
        BUTTON_EDITAR2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUTTON_EDITAR2.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_EDITAR2.setText("CONSULTAR VEICULO");
        BUTTON_EDITAR2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON_EDITAR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_EDITAR2ActionPerformed(evt);
            }
        });

        BUTTON_EDITAR3.setBackground(new java.awt.Color(0, 204, 51));
        BUTTON_EDITAR3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUTTON_EDITAR3.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_EDITAR3.setText("CONSULTAR SERVIÇO");
        BUTTON_EDITAR3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON_EDITAR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_EDITAR3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HEADER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BUTTON_EXCLUIR, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BUTTON_EDITAR, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(137, 137, 137))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BG_INPUT_LOGRADOURO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BG_INPUT_CEP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BG_INPUT_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BG_INPUT_DTNASCIMENTO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(BG_INPUT_NOME, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BG_INPUT_EMAIL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BG_INPUT_BAIRRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BG_INPUT_CIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BUTTON_EDITAR1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TEXT_TITLE2)
                                    .addGap(228, 228, 228))))
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TEXT_TITLE1)
                        .addGap(244, 244, 244))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(913, Short.MAX_VALUE)
                    .addComponent(BUTTON_EDITAR2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(196, 196, 196)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(929, Short.MAX_VALUE)
                    .addComponent(BUTTON_EDITAR3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(180, 180, 180)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HEADER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(TEXT_TITLE1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(TEXT_TITLE2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(BUTTON_EDITAR1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(BG_INPUT_NOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BG_INPUT_CPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BG_INPUT_DTNASCIMENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BG_INPUT_EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BG_INPUT_LOGRADOURO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BG_INPUT_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BG_INPUT_CIDADE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BG_INPUT_BAIRRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(BUTTON_EDITAR, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BUTTON_EXCLUIR, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(401, Short.MAX_VALUE)
                    .addComponent(BUTTON_EDITAR2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(375, 375, 375)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(742, Short.MAX_VALUE)
                    .addComponent(BUTTON_EDITAR3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(34, 34, 34)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BUTTON_EDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_EDITARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BUTTON_EDITARActionPerformed

    private void BUTTON_EXCLUIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_EXCLUIRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BUTTON_EXCLUIRActionPerformed

    private void BUTTON_EDITAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_EDITAR1ActionPerformed
        this.formCadastrarOrdemDeServico.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BUTTON_EDITAR1ActionPerformed

    private void BUTTON_EDITAR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_EDITAR2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BUTTON_EDITAR2ActionPerformed

    private void BUTTON_EDITAR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_EDITAR3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BUTTON_EDITAR3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG_INPUT_BAIRRO;
    private javax.swing.JPanel BG_INPUT_CEP;
    private javax.swing.JPanel BG_INPUT_CIDADE;
    private javax.swing.JPanel BG_INPUT_CPF;
    private javax.swing.JPanel BG_INPUT_DTNASCIMENTO;
    private javax.swing.JPanel BG_INPUT_EMAIL;
    private javax.swing.JPanel BG_INPUT_LOGRADOURO;
    private javax.swing.JPanel BG_INPUT_NOME;
    private javax.swing.JButton BUTTON_EDITAR;
    private javax.swing.JButton BUTTON_EDITAR1;
    private javax.swing.JButton BUTTON_EDITAR2;
    private javax.swing.JButton BUTTON_EDITAR3;
    private javax.swing.JButton BUTTON_EXCLUIR;
    private javax.swing.JPanel HEADER;
    private javax.swing.JTextPane INPUT_BAIRRO;
    private javax.swing.JTextPane INPUT_CEP;
    private javax.swing.JTextPane INPUT_CIDADE;
    private javax.swing.JTextPane INPUT_CPF;
    private com.toedter.calendar.JDateChooser INPUT_DTNASCIMENTO;
    private javax.swing.JTextPane INPUT_EMAIL;
    private javax.swing.JTextPane INPUT_LOGRADOURO;
    private javax.swing.JTextPane INPUT_NOME;
    private javax.swing.JLabel TEXT_BAIRRO;
    private javax.swing.JLabel TEXT_CEP;
    private javax.swing.JLabel TEXT_CIDADE;
    private javax.swing.JLabel TEXT_CPF;
    private javax.swing.JLabel TEXT_DTNASCIMENTO;
    private javax.swing.JLabel TEXT_EMAIL;
    private javax.swing.JLabel TEXT_LOGRADOURO;
    private javax.swing.JLabel TEXT_NOME;
    private javax.swing.JLabel TEXT_TITLE;
    private javax.swing.JLabel TEXT_TITLE1;
    private javax.swing.JLabel TEXT_TITLE2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
