/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.ControllerVeiculo;
import Forms.FormListarVeiculo;
import Interfaces.FalhaException;
import Models.Veiculo;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author oseas
 */
public class FormConsultarVeiculo extends javax.swing.JFrame {
    
    private Veiculo veiculo;
    private final ControllerVeiculo controllerVeiculo = new ControllerVeiculo();
    private final FormAtualizarVeiculo formAtualizarVeiculo = new FormAtualizarVeiculo();

    public Veiculo getVeiculo() {
        return veiculo;
    }

    public void setVeiculo(Veiculo veiculo) {
        try {
            this.veiculo = veiculo;
            controllerVeiculo.setVeiculo(veiculo);
            controllerVeiculo.preencherForm(INPUT_PLACA, INPUT_QUILOMETRAGEM, INPUT_COR, INPUT_COMBUSTIVEL, INPUT_MODELO, INPUT_CLASSIFICACAO, INPUT_DTFABRICACAO);
        } catch (FalhaException ex) {
            Logger.getLogger(FormConsultarVeiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    /**
     * Creates new form FormConsultarVeiculo
     */
    public FormConsultarVeiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HEADER = new javax.swing.JPanel();
        TEXT_TITLE = new javax.swing.JLabel();
        BG_INPUT_DTFABRICACAO = new javax.swing.JPanel();
        TEXT_DTFABRICACAO = new javax.swing.JLabel();
        INPUT_DTFABRICACAO = new com.toedter.calendar.JDateChooser();
        BG_INPUT_QUILOMETRAGEM = new javax.swing.JPanel();
        TEXT_QUILOMETRAGEM = new javax.swing.JLabel();
        INPUT_QUILOMETRAGEM = new javax.swing.JTextPane();
        BG_INPUT_PLACA = new javax.swing.JPanel();
        TEXT_PLACA = new javax.swing.JLabel();
        INPUT_PLACA = new javax.swing.JTextPane();
        BG_INPUT_COR = new javax.swing.JPanel();
        TEXT_COR = new javax.swing.JLabel();
        INPUT_COR = new javax.swing.JTextPane();
        BUTTON_CADASTRAR = new javax.swing.JButton();
        BG_INPUT_COMBUSTIVEL = new javax.swing.JPanel();
        TEXT_COMBUSTIVEL = new javax.swing.JLabel();
        INPUT_COMBUSTIVEL = new javax.swing.JTextPane();
        BG_INPUT_MODELO = new javax.swing.JPanel();
        TEXT_MODELO = new javax.swing.JLabel();
        INPUT_MODELO = new javax.swing.JTextPane();
        BG_INPUT_CLASSIFICACAO = new javax.swing.JPanel();
        TEXT_CLASSIFICACAO = new javax.swing.JLabel();
        INPUT_CLASSIFICACAO = new javax.swing.JTextPane();
        BUTTON_CADASTRAR1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HEADER.setBackground(new java.awt.Color(159, 172, 172));

        TEXT_TITLE.setFont(new java.awt.Font("Arial", 1, 35)); // NOI18N
        TEXT_TITLE.setForeground(new java.awt.Color(255, 255, 255));
        TEXT_TITLE.setText("CONSULTAR VEICULO");

        javax.swing.GroupLayout HEADERLayout = new javax.swing.GroupLayout(HEADER);
        HEADER.setLayout(HEADERLayout);
        HEADERLayout.setHorizontalGroup(
            HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HEADERLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(TEXT_TITLE)
                .addGap(200, 200, 200))
        );
        HEADERLayout.setVerticalGroup(
            HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HEADERLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(TEXT_TITLE, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        BG_INPUT_DTFABRICACAO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_DTFABRICACAO.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_DTFABRICACAO.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_DTFABRICACAO.setText("Data fabricação:");

        INPUT_DTFABRICACAO.setEnabled(false);

        javax.swing.GroupLayout BG_INPUT_DTFABRICACAOLayout = new javax.swing.GroupLayout(BG_INPUT_DTFABRICACAO);
        BG_INPUT_DTFABRICACAO.setLayout(BG_INPUT_DTFABRICACAOLayout);
        BG_INPUT_DTFABRICACAOLayout.setHorizontalGroup(
            BG_INPUT_DTFABRICACAOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_DTFABRICACAOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXT_DTFABRICACAO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(INPUT_DTFABRICACAO, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );
        BG_INPUT_DTFABRICACAOLayout.setVerticalGroup(
            BG_INPUT_DTFABRICACAOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_DTFABRICACAOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_INPUT_DTFABRICACAOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(INPUT_DTFABRICACAO, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_DTFABRICACAO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BG_INPUT_QUILOMETRAGEM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_QUILOMETRAGEM.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_QUILOMETRAGEM.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_QUILOMETRAGEM.setText("Quilometrage:");

        INPUT_QUILOMETRAGEM.setBorder(null);
        INPUT_QUILOMETRAGEM.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_QUILOMETRAGEM.setToolTipText("Quantidade");
        INPUT_QUILOMETRAGEM.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        INPUT_QUILOMETRAGEM.setEnabled(false);

        javax.swing.GroupLayout BG_INPUT_QUILOMETRAGEMLayout = new javax.swing.GroupLayout(BG_INPUT_QUILOMETRAGEM);
        BG_INPUT_QUILOMETRAGEM.setLayout(BG_INPUT_QUILOMETRAGEMLayout);
        BG_INPUT_QUILOMETRAGEMLayout.setHorizontalGroup(
            BG_INPUT_QUILOMETRAGEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_QUILOMETRAGEMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXT_QUILOMETRAGEM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_QUILOMETRAGEM)
                .addContainerGap())
        );
        BG_INPUT_QUILOMETRAGEMLayout.setVerticalGroup(
            BG_INPUT_QUILOMETRAGEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_QUILOMETRAGEMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_INPUT_QUILOMETRAGEMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_QUILOMETRAGEM, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_QUILOMETRAGEM, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BG_INPUT_PLACA.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_PLACA.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_PLACA.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_PLACA.setText("Placa:");

        INPUT_PLACA.setBorder(null);
        INPUT_PLACA.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_PLACA.setToolTipText("Quantidade");
        INPUT_PLACA.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        INPUT_PLACA.setEnabled(false);

        javax.swing.GroupLayout BG_INPUT_PLACALayout = new javax.swing.GroupLayout(BG_INPUT_PLACA);
        BG_INPUT_PLACA.setLayout(BG_INPUT_PLACALayout);
        BG_INPUT_PLACALayout.setHorizontalGroup(
            BG_INPUT_PLACALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_PLACALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXT_PLACA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_PLACA, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );
        BG_INPUT_PLACALayout.setVerticalGroup(
            BG_INPUT_PLACALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_PLACALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_INPUT_PLACALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_PLACA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_PLACA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BG_INPUT_COR.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_COR.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_COR.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_COR.setText("Cor:");

        INPUT_COR.setBorder(null);
        INPUT_COR.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_COR.setToolTipText("Quantidade");
        INPUT_COR.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        INPUT_COR.setEnabled(false);

        javax.swing.GroupLayout BG_INPUT_CORLayout = new javax.swing.GroupLayout(BG_INPUT_COR);
        BG_INPUT_COR.setLayout(BG_INPUT_CORLayout);
        BG_INPUT_CORLayout.setHorizontalGroup(
            BG_INPUT_CORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_CORLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXT_COR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(INPUT_COR)
                .addContainerGap())
        );
        BG_INPUT_CORLayout.setVerticalGroup(
            BG_INPUT_CORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_CORLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_INPUT_CORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_COR, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_COR, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BUTTON_CADASTRAR.setBackground(new java.awt.Color(204, 51, 0));
        BUTTON_CADASTRAR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUTTON_CADASTRAR.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_CADASTRAR.setText("EXCLUIR");
        BUTTON_CADASTRAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON_CADASTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_CADASTRARActionPerformed(evt);
            }
        });

        BG_INPUT_COMBUSTIVEL.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_COMBUSTIVEL.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_COMBUSTIVEL.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_COMBUSTIVEL.setText("Combustivel:");

        INPUT_COMBUSTIVEL.setBorder(null);
        INPUT_COMBUSTIVEL.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_COMBUSTIVEL.setToolTipText("Quantidade");
        INPUT_COMBUSTIVEL.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        INPUT_COMBUSTIVEL.setEnabled(false);
        INPUT_COMBUSTIVEL.setFocusCycleRoot(false);

        javax.swing.GroupLayout BG_INPUT_COMBUSTIVELLayout = new javax.swing.GroupLayout(BG_INPUT_COMBUSTIVEL);
        BG_INPUT_COMBUSTIVEL.setLayout(BG_INPUT_COMBUSTIVELLayout);
        BG_INPUT_COMBUSTIVELLayout.setHorizontalGroup(
            BG_INPUT_COMBUSTIVELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_COMBUSTIVELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXT_COMBUSTIVEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_COMBUSTIVEL, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );
        BG_INPUT_COMBUSTIVELLayout.setVerticalGroup(
            BG_INPUT_COMBUSTIVELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_COMBUSTIVELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_INPUT_COMBUSTIVELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_COMBUSTIVEL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_COMBUSTIVEL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BG_INPUT_MODELO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_MODELO.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_MODELO.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_MODELO.setText("Modelo:");

        INPUT_MODELO.setBorder(null);
        INPUT_MODELO.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_MODELO.setToolTipText("Quantidade");
        INPUT_MODELO.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        INPUT_MODELO.setEnabled(false);

        javax.swing.GroupLayout BG_INPUT_MODELOLayout = new javax.swing.GroupLayout(BG_INPUT_MODELO);
        BG_INPUT_MODELO.setLayout(BG_INPUT_MODELOLayout);
        BG_INPUT_MODELOLayout.setHorizontalGroup(
            BG_INPUT_MODELOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_MODELOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXT_MODELO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_MODELO, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        BG_INPUT_MODELOLayout.setVerticalGroup(
            BG_INPUT_MODELOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_MODELOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_INPUT_MODELOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_MODELO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_MODELO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BG_INPUT_CLASSIFICACAO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_CLASSIFICACAO.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_CLASSIFICACAO.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_CLASSIFICACAO.setText("Classificação:");

        INPUT_CLASSIFICACAO.setBorder(null);
        INPUT_CLASSIFICACAO.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_CLASSIFICACAO.setToolTipText("Quantidade");
        INPUT_CLASSIFICACAO.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        INPUT_CLASSIFICACAO.setEnabled(false);

        javax.swing.GroupLayout BG_INPUT_CLASSIFICACAOLayout = new javax.swing.GroupLayout(BG_INPUT_CLASSIFICACAO);
        BG_INPUT_CLASSIFICACAO.setLayout(BG_INPUT_CLASSIFICACAOLayout);
        BG_INPUT_CLASSIFICACAOLayout.setHorizontalGroup(
            BG_INPUT_CLASSIFICACAOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_CLASSIFICACAOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXT_CLASSIFICACAO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_CLASSIFICACAO)
                .addContainerGap())
        );
        BG_INPUT_CLASSIFICACAOLayout.setVerticalGroup(
            BG_INPUT_CLASSIFICACAOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_CLASSIFICACAOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_INPUT_CLASSIFICACAOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_CLASSIFICACAO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_CLASSIFICACAO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BUTTON_CADASTRAR1.setBackground(new java.awt.Color(0, 102, 153));
        BUTTON_CADASTRAR1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUTTON_CADASTRAR1.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_CADASTRAR1.setText("EDITAR");
        BUTTON_CADASTRAR1.setActionCommand("editar");
        BUTTON_CADASTRAR1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON_CADASTRAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_CADASTRAR1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HEADER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BG_INPUT_QUILOMETRAGEM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BG_INPUT_DTFABRICACAO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BG_INPUT_COR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BG_INPUT_PLACA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BG_INPUT_COMBUSTIVEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BG_INPUT_MODELO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BG_INPUT_CLASSIFICACAO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BUTTON_CADASTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(139, 139, 139)
                    .addComponent(BUTTON_CADASTRAR1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(440, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HEADER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BG_INPUT_DTFABRICACAO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BG_INPUT_PLACA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BG_INPUT_QUILOMETRAGEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BG_INPUT_COR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BG_INPUT_COMBUSTIVEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BG_INPUT_MODELO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BG_INPUT_CLASSIFICACAO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(89, 89, 89)
                .addComponent(BUTTON_CADASTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(488, Short.MAX_VALUE)
                    .addComponent(BUTTON_CADASTRAR1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(77, 77, 77)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BUTTON_CADASTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_CADASTRARActionPerformed
        try {
            this.veiculo.excluir();
            this.setVisible(false);
            FormListarVeiculo.atualizar();
        } catch (FalhaException ex) {
        }
    }//GEN-LAST:event_BUTTON_CADASTRARActionPerformed

    private void BUTTON_CADASTRAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_CADASTRAR1ActionPerformed
        formAtualizarVeiculo.setVeiculo(veiculo);
        formAtualizarVeiculo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BUTTON_CADASTRAR1ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormConsultarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormConsultarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormConsultarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormConsultarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormConsultarVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG_INPUT_CLASSIFICACAO;
    private javax.swing.JPanel BG_INPUT_COMBUSTIVEL;
    private javax.swing.JPanel BG_INPUT_COR;
    private javax.swing.JPanel BG_INPUT_DTFABRICACAO;
    private javax.swing.JPanel BG_INPUT_MODELO;
    private javax.swing.JPanel BG_INPUT_PLACA;
    private javax.swing.JPanel BG_INPUT_QUILOMETRAGEM;
    private javax.swing.JButton BUTTON_CADASTRAR;
    private javax.swing.JButton BUTTON_CADASTRAR1;
    private javax.swing.JPanel HEADER;
    private javax.swing.JTextPane INPUT_CLASSIFICACAO;
    private javax.swing.JTextPane INPUT_COMBUSTIVEL;
    private javax.swing.JTextPane INPUT_COR;
    private com.toedter.calendar.JDateChooser INPUT_DTFABRICACAO;
    private javax.swing.JTextPane INPUT_MODELO;
    private javax.swing.JTextPane INPUT_PLACA;
    private javax.swing.JTextPane INPUT_QUILOMETRAGEM;
    private javax.swing.JLabel TEXT_CLASSIFICACAO;
    private javax.swing.JLabel TEXT_COMBUSTIVEL;
    private javax.swing.JLabel TEXT_COR;
    private javax.swing.JLabel TEXT_DTFABRICACAO;
    private javax.swing.JLabel TEXT_MODELO;
    private javax.swing.JLabel TEXT_PLACA;
    private javax.swing.JLabel TEXT_QUILOMETRAGEM;
    private javax.swing.JLabel TEXT_TITLE;
    // End of variables declaration//GEN-END:variables
}
