/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Views;

import Controllers.DAO;
import br.dev.lomm.automecanicapoo.database.Funcionario;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oseas
 */
public class FormListarFuncionario extends javax.swing.JInternalFrame {

    private FormCadastrarFuncionario formCadastrarFuncionario;
    private static DefaultTableModel Tabela;
    private static Funcionario funcionarioDAO = new Funcionario();
    private FormConsultarFuncionario formConsultarFuncionario;
    /**
     * Creates new form FormListarFuncionario
     */
    public FormListarFuncionario() {
        initComponents();
        setTabela((DefaultTableModel) TABLE_PRODUTOS.getModel());
        atualizarTabela();
    }
    
    private static void setTabela(DefaultTableModel tabela){
        Tabela = tabela;
    }
    
    public static void atualizarTabela(){
        Tabela.getDataVector().removeAllElements();
        for (Funcionario fun : funcionarioDAO.getFuncionarios()) {
            String data[] = {fun.getIdfuncionario()+"",fun.getFunIdpessoa().getPesNome(),fun.getFunIdcargo().getCargDescricao()};
            Tabela.addRow(data);   
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TABLE = new javax.swing.JScrollPane();
        TABLE_PRODUTOS = new javax.swing.JTable();
        TEXT_PESQUISA = new javax.swing.JLabel();
        BUTTON_CONSULTAR = new javax.swing.JButton();
        HEADER = new javax.swing.JPanel();
        TEXT_TITLE = new javax.swing.JLabel();
        BUTTON_CADASTRAR = new javax.swing.JButton();
        BUTTON_PESQUISAR = new javax.swing.JButton();
        INPUT_PESQUISA = new javax.swing.JTextPane();

        TABLE_PRODUTOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Cargo"
            }
        ));
        TABLE.setViewportView(TABLE_PRODUTOS);

        TEXT_PESQUISA.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        TEXT_PESQUISA.setText("Pequisa:");

        BUTTON_CONSULTAR.setBackground(new java.awt.Color(0, 204, 204));
        BUTTON_CONSULTAR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUTTON_CONSULTAR.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_CONSULTAR.setText("CONSULTAR");
        BUTTON_CONSULTAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON_CONSULTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_CONSULTARActionPerformed(evt);
            }
        });

        HEADER.setBackground(new java.awt.Color(159, 172, 172));

        TEXT_TITLE.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        TEXT_TITLE.setForeground(new java.awt.Color(255, 255, 255));
        TEXT_TITLE.setText("LISTAR FUNCIONARIO");

        javax.swing.GroupLayout HEADERLayout = new javax.swing.GroupLayout(HEADER);
        HEADER.setLayout(HEADERLayout);
        HEADERLayout.setHorizontalGroup(
            HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HEADERLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TEXT_TITLE)
                .addContainerGap())
        );
        HEADERLayout.setVerticalGroup(
            HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TEXT_TITLE, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        BUTTON_CADASTRAR.setBackground(new java.awt.Color(0, 102, 0));
        BUTTON_CADASTRAR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUTTON_CADASTRAR.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_CADASTRAR.setText("CADASTRAR");
        BUTTON_CADASTRAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON_CADASTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_CADASTRARActionPerformed(evt);
            }
        });

        BUTTON_PESQUISAR.setBackground(new java.awt.Color(0, 204, 255));
        BUTTON_PESQUISAR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUTTON_PESQUISAR.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_PESQUISAR.setText("PESQUISAR");
        BUTTON_PESQUISAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON_PESQUISAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_PESQUISARActionPerformed(evt);
            }
        });

        INPUT_PESQUISA.setBorder(null);
        INPUT_PESQUISA.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_PESQUISA.setToolTipText("Quantidade");
        INPUT_PESQUISA.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HEADER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TEXT_PESQUISA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(INPUT_PESQUISA)
                                .addGap(18, 18, 18)
                                .addComponent(BUTTON_PESQUISAR, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TABLE, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(BUTTON_CONSULTAR, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BUTTON_CADASTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HEADER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BUTTON_PESQUISAR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(INPUT_PESQUISA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_PESQUISA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(TABLE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BUTTON_CONSULTAR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUTTON_CADASTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BUTTON_CONSULTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_CONSULTARActionPerformed
       int linha = TABLE_PRODUTOS.getSelectedRow();
       int codigoProduto = Integer.parseInt(TABLE_PRODUTOS.getValueAt(linha,0).toString());
       Funcionario funcionario = DAO.getInstance().find(Funcionario.class, codigoProduto);
       if(funcionario instanceof Funcionario){
            if(!(this.formConsultarFuncionario instanceof FormConsultarFuncionario)){
                this.formConsultarFuncionario = new FormConsultarFuncionario();
            }
            this.formConsultarFuncionario.setFuncionario(funcionario);
            this.formConsultarFuncionario.setVisible(true);
       }
    }//GEN-LAST:event_BUTTON_CONSULTARActionPerformed

    private void BUTTON_CADASTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_CADASTRARActionPerformed
        if(!(this.formCadastrarFuncionario instanceof FormCadastrarFuncionario)){
            this.formCadastrarFuncionario = new FormCadastrarFuncionario();
        }
        this.formCadastrarFuncionario.setVisible(true);
    }//GEN-LAST:event_BUTTON_CADASTRARActionPerformed

    private void BUTTON_PESQUISARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_PESQUISARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BUTTON_PESQUISARActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUTTON_CADASTRAR;
    private javax.swing.JButton BUTTON_CONSULTAR;
    private javax.swing.JButton BUTTON_PESQUISAR;
    private javax.swing.JPanel HEADER;
    private javax.swing.JTextPane INPUT_PESQUISA;
    private javax.swing.JScrollPane TABLE;
    private javax.swing.JTable TABLE_PRODUTOS;
    private javax.swing.JLabel TEXT_PESQUISA;
    private javax.swing.JLabel TEXT_TITLE;
    // End of variables declaration//GEN-END:variables
}
