/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Views;

import Controllers.ControllerLote;
import Interfaces.FalhaException;
import Models.Estoque;

/**
 *
 * @author oseas
 */
public class FormAtualizarEstoque extends javax.swing.JFrame {

    private Estoque estoque;
    private final ControllerLote controllerLote = new ControllerLote();
        
    /**
     * Creates new form FormAtualizarEstoque
     */
    public FormAtualizarEstoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG_INPUT_QUANTIDADE = new javax.swing.JPanel();
        TEXT_QUANTIDADE = new javax.swing.JLabel();
        INPUT_QUANTIDADE = new javax.swing.JTextPane();
        HEADER = new javax.swing.JPanel();
        TEXT_TITLE = new javax.swing.JLabel();
        BUTTON_ATUALIZAR = new javax.swing.JButton();
        BG_INPUT_PRECO = new javax.swing.JPanel();
        TEXT_PRECO = new javax.swing.JLabel();
        INPUT_PRECO = new javax.swing.JTextPane();
        BG_INPUT_NOTA = new javax.swing.JPanel();
        TEXT_NOTA = new javax.swing.JLabel();
        INPUT_NOTA = new javax.swing.JTextPane();
        BG_INPUT_PRODUTO = new javax.swing.JPanel();
        TEXT_PRODUTO = new javax.swing.JLabel();
        INPUT_PRODUTO = new javax.swing.JTextPane();

        BG_INPUT_QUANTIDADE.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_QUANTIDADE.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_QUANTIDADE.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_QUANTIDADE.setText("Quantidade:");

        INPUT_QUANTIDADE.setBorder(null);
        INPUT_QUANTIDADE.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_QUANTIDADE.setToolTipText("Quantidade");
        INPUT_QUANTIDADE.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout BG_INPUT_QUANTIDADELayout = new javax.swing.GroupLayout(BG_INPUT_QUANTIDADE);
        BG_INPUT_QUANTIDADE.setLayout(BG_INPUT_QUANTIDADELayout);
        BG_INPUT_QUANTIDADELayout.setHorizontalGroup(
            BG_INPUT_QUANTIDADELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_QUANTIDADELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXT_QUANTIDADE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_QUANTIDADE, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        BG_INPUT_QUANTIDADELayout.setVerticalGroup(
            BG_INPUT_QUANTIDADELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_QUANTIDADELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_INPUT_QUANTIDADELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_QUANTIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_QUANTIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        HEADER.setBackground(new java.awt.Color(159, 172, 172));

        TEXT_TITLE.setFont(new java.awt.Font("Arial", 1, 35)); // NOI18N
        TEXT_TITLE.setForeground(new java.awt.Color(255, 255, 255));
        TEXT_TITLE.setText("ATUALIZAR ESTOQUE");

        javax.swing.GroupLayout HEADERLayout = new javax.swing.GroupLayout(HEADER);
        HEADER.setLayout(HEADERLayout);
        HEADERLayout.setHorizontalGroup(
            HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HEADERLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(TEXT_TITLE)
                .addGap(200, 200, 200))
        );
        HEADERLayout.setVerticalGroup(
            HEADERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HEADERLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(TEXT_TITLE, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        BUTTON_ATUALIZAR.setBackground(new java.awt.Color(0, 204, 0));
        BUTTON_ATUALIZAR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUTTON_ATUALIZAR.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_ATUALIZAR.setText("ATUALIZAR");
        BUTTON_ATUALIZAR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BUTTON_ATUALIZAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_ATUALIZARActionPerformed(evt);
            }
        });

        BG_INPUT_PRECO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_PRECO.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_PRECO.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_PRECO.setText("Preço:");

        INPUT_PRECO.setBorder(null);
        INPUT_PRECO.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_PRECO.setToolTipText("Quantidade");
        INPUT_PRECO.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout BG_INPUT_PRECOLayout = new javax.swing.GroupLayout(BG_INPUT_PRECO);
        BG_INPUT_PRECO.setLayout(BG_INPUT_PRECOLayout);
        BG_INPUT_PRECOLayout.setHorizontalGroup(
            BG_INPUT_PRECOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_PRECOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXT_PRECO, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_PRECO, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        BG_INPUT_PRECOLayout.setVerticalGroup(
            BG_INPUT_PRECOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_PRECOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_INPUT_PRECOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_PRECO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_PRECO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BG_INPUT_NOTA.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_NOTA.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_NOTA.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_NOTA.setText("Nota:");

        INPUT_NOTA.setBorder(null);
        INPUT_NOTA.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_NOTA.setToolTipText("Quantidade");
        INPUT_NOTA.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout BG_INPUT_NOTALayout = new javax.swing.GroupLayout(BG_INPUT_NOTA);
        BG_INPUT_NOTA.setLayout(BG_INPUT_NOTALayout);
        BG_INPUT_NOTALayout.setHorizontalGroup(
            BG_INPUT_NOTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_NOTALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXT_NOTA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_NOTA)
                .addGap(2, 2, 2))
        );
        BG_INPUT_NOTALayout.setVerticalGroup(
            BG_INPUT_NOTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_NOTALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_INPUT_NOTALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_NOTA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_NOTA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BG_INPUT_PRODUTO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TEXT_PRODUTO.setBackground(new java.awt.Color(238, 238, 238));
        TEXT_PRODUTO.setFont(new java.awt.Font("Arial", 0, 23)); // NOI18N
        TEXT_PRODUTO.setText("Produto:");

        INPUT_PRODUTO.setBorder(null);
        INPUT_PRODUTO.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        INPUT_PRODUTO.setToolTipText("Quantidade");
        INPUT_PRODUTO.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout BG_INPUT_PRODUTOLayout = new javax.swing.GroupLayout(BG_INPUT_PRODUTO);
        BG_INPUT_PRODUTO.setLayout(BG_INPUT_PRODUTOLayout);
        BG_INPUT_PRODUTOLayout.setHorizontalGroup(
            BG_INPUT_PRODUTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_PRODUTOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXT_PRODUTO, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_PRODUTO, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addContainerGap())
        );
        BG_INPUT_PRODUTOLayout.setVerticalGroup(
            BG_INPUT_PRODUTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BG_INPUT_PRODUTOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BG_INPUT_PRODUTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_PRODUTO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEXT_PRODUTO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HEADER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BUTTON_ATUALIZAR, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(247, 247, 247))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BG_INPUT_PRECO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BG_INPUT_NOTA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BG_INPUT_PRODUTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BG_INPUT_QUANTIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(84, 84, 84))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HEADER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BG_INPUT_PRODUTO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BG_INPUT_QUANTIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BG_INPUT_NOTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BG_INPUT_PRECO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BUTTON_ATUALIZAR, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BUTTON_ATUALIZARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_ATUALIZARActionPerformed
        try{
            controllerLote.setCampos(INPUT_QUANTIDADE, INPUT_PRECO);
            controllerLote.validarDados();
            controllerLote.getEstoque().atualizar();
            this.setVisible(false);
        }catch(FalhaException $erro){
            
        }
    }//GEN-LAST:event_BUTTON_ATUALIZARActionPerformed

    
    public void setEstoque(Estoque estoque){
        this.estoque = estoque;
        controllerLote.preencherForm(INPUT_PRODUTO, INPUT_QUANTIDADE, INPUT_PRECO, INPUT_NOTA);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG_INPUT_NOTA;
    private javax.swing.JPanel BG_INPUT_PRECO;
    private javax.swing.JPanel BG_INPUT_PRODUTO;
    private javax.swing.JPanel BG_INPUT_QUANTIDADE;
    private javax.swing.JButton BUTTON_ATUALIZAR;
    private javax.swing.JPanel HEADER;
    private javax.swing.JTextPane INPUT_NOTA;
    private javax.swing.JTextPane INPUT_PRECO;
    private javax.swing.JTextPane INPUT_PRODUTO;
    private javax.swing.JTextPane INPUT_QUANTIDADE;
    private javax.swing.JLabel TEXT_NOTA;
    private javax.swing.JLabel TEXT_PRECO;
    private javax.swing.JLabel TEXT_PRODUTO;
    private javax.swing.JLabel TEXT_QUANTIDADE;
    private javax.swing.JLabel TEXT_TITLE;
    // End of variables declaration//GEN-END:variables
}
